// Tao Du
// taodu@csail.mit.edu
// Octo 18, 2015
//
// Calibrate the thrust generated by the propeller.

#include <AP_HAL/AP_HAL.h>
#include <AP_Math/AP_Math.h>

const AP_HAL::HAL& hal = AP_HAL::get_HAL();

const int prop_num = 4;
const uint16_t pwm_min = 1000;
uint16_t last_value = pwm_min;

void setup(void) {
    hal.console->println_P(PSTR("Propeller Measurement."));

    // For each propeller, initialize with the minimal throttle value.
    for (int i = 0; i < prop_num; ++i) {
        hal.rcout->enable_ch(i);
        hal.rcout->write(i, pwm_min);
    }
}

void loop(void)
{
    // Get input signal from channel 3(throttle in mode 2).
    uint16_t v = hal.rcin->read(2);
    // Only output the signal when the difference is greater than threshold
    // to avoid verbose outputs.
    const int threshold = 3;
    if (abs((int)v - (int)last_value) > threshold)
        hal.console->printf("%u\n", v);
    last_value = v;
    // Send out the signal.
    hal.rcout->write(2, v);
    hal.scheduler->delay(5);
}

AP_HAL_MAIN();
