function [fitresult, gof] = quad_fit(normalized_pwm, normalized_thrust)
%CREATEFIT(NORMALIZED_PWM,NORMALIZED_THRUST)
%  Create a fit.
%
%  Data for 'quad_fit' fit:
%      X Input : normalized_pwm
%      Y Output: normalized_thrust
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Oct-2015 13:44:21


%% Fit: 'quad_fit'.
[xData, yData] = prepareCurveData( normalized_pwm, normalized_thrust );

% Set up fittype and options.
ft = fittype( 'a*(x-b)^2', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.231471516773163 0.810292563200234];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'quad_fit' );
h = plot( fitresult, xData, yData );
legend( h, 'normalized_thrust vs. normalized_pwm', 'quad_fit', 'Location', 'NorthEast' );
% Label axes
xlabel normalized_pwm
ylabel normalized_thrust
grid on


